### ISSUE TITLE
README will conflict when pulling

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#1]
@gvwilson `README` will conflict when pulling this repo from `site`, `workshops` and `lessons`. Could we remove it from the history?

**Comment by gvwilson** [comment]
Yes.  (And please note, mail to your unicamp address is failing.)

**Comment by wking** [comment]
On Tue, Jan 27, 2015 at 06:50:45AM -0800, Raniere Silva wrote:
> @gvwilson `README` will conflict when pulling this repo from `site`,
> `workshops` and `lessons`. Could we remove it from the history?

I'd recommend the same "doc directory with a static link from the
README" approach I suggested for lesson-template
(swcarpentry/lesson-template#124).  Then you get access to the style
docs with a single click from the swcarpentry/styles README, and also
have access to those docs in repositories that are merging the styles.

Alternatively, you could merge the styles with their root README into
downstream repositories using a subtree merge.  Drop the css directory
here, and then merge this whole branch into the downstream repository
under css/.

**Comment by r-gaia-cs** [comment]
> hen merge this whole branch into the downstream repository under css/

@wking Could you provide me with some reference about which command should I use for that? Thanks in advance.

**Comment by wking** [comment]
On Wed, Jan 28, 2015 at 03:06:32AM -0800, Raniere Silva wrote:
> > hen merge this whole branch into the downstream repository under css/
>
> @wking Could you provide me with some reference about which command
> should I use for that? Thanks in advance.

For the subtree merge, see [1].  Workflow for the initial merge looks
like:

  $ git merge -s ours --no-commit styles/master
  $ git read-tree --prefix=ssl/ -u styles/master
  $ git commit -v

Subsequent merges look like:

  $ git pull -s subtree styles master

[1]: https://www.kernel.org/pub/software/scm/git/docs/howto/using-merge-subtree.html
