### ISSUE TITLE
Table CSS

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#101]
For the workshop page I prefer to have

![screencapture-localhost-4000-1473428791425](https://cloud.githubusercontent.com/assets/1506457/18389177/91f29c48-769c-11e6-9379-fb6c0c35c2d7.png)

instead of 

![screencapture-localhost-4000-1473428818062](https://cloud.githubusercontent.com/assets/1506457/18389179/986e13c2-769c-11e6-9169-e65f2fb231f7.png)

**See the difference on the width of the tables.**

@gvwilson Why did you make the following change on Bootstrap?

```
.table {
  /* width: 100%; -- CHANGE -- */
  max-width: 100%;
  margin-bottom: 20px;
}
```

**Comment by gvwilson** [comment]
I preferred the narrower - if you'd like to take the wider to the maintainers for discussion, please do.

**Comment by naupaka** [comment]
I like narrow, myself, but it's not a strong preference.

**Comment by iglpdc** [comment]
Either is fine to me.

**Comment by fmichonneau** [comment]
+1 for narrower

**Comment by gdevenyi** [comment]
+1 wider

**Comment by mkuzak** [comment]
+1 wider

**Comment by tbekolay** [comment]
+1 wider, but it's not a strong preference.

**Comment by rgaiacs** [comment]
So far we had +3 for narrow and +4 for wider. @gvwilson and @k8hertweck I will send I pull request to implement this if it is OK for you.
