### ISSUE TITLE
Add test in lesson_check.py to make sure 'root' is set to '..' in configuration file

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/styles#102]
Also check that root variable is set to '.' in `index.md`.

**Comment by wking** [comment]
You can drop all the `root` stuff with [Jekyll 3.3 and `relative_url`][1].

[1]: https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

**Comment by gvwilson** [comment]
That's the best news I've had all day.  We'll tackle it after December's 
release.

**Comment by rgaiacs** [comment]
I think that we implemented this. @gvwilson please reopen if I'm wrong.

**Comment by gvwilson** [comment]
Yes, it has been implemented, but it would be best to verify that by 
inspecting the code or running `lesson_check.py` with a case that ought 
to fail before closing the issue.
