### ISSUE TITLE
Re-add PR template

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/styles#106]
We used to have something like [this](https://github.com/blog/2111-issue-and-pull-request-templates) set up, at least on the r-novice-inflammation lesson, but potentially it got removed during the last big update. See discussion [here](https://github.com/swcarpentry/r-novice-gapminder/issues/206). Should be straightforward, just need to add a `PULL_REQUEST_TEMPLATE.md` to the root or else in a `.github` folder. @gvwilson @fmichonneau

**Comment by rgaiacs** [comment]
@naupaka Thanks for the pull request. I believe that changes on the `PULL_REQUEST_TEMPLATE.md` of this repo will conflict with the same file on other repos and because of it wasn't included.

**Comment by rgaiacs** [comment]
I believe that @ErinBecker resolved this issue, see https://github.com/swcarpentry/styles/tree/gh-pages/.github. I'm closing it.
