### ISSUE TITLE
2em padding on the left for lists

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#115]
@maxim-belkin created https://github.com/swcarpentry/lesson-example/pull/83 for `lesson.scss` but I think that this maybe need to be fixed for other pages.

@gvwilson Could you point someone that had worked on the CSS more than me to help with this one?

**Comment by maxim-belkin** [comment]
@rgaiacs thanks for pointing to the right repo. I can submit the same PR here if necessary.

Just to clarify, the issue with numbered lists can be seen [here](http://swcarpentry.github.io/lesson-example/).

@rgaiacs Also, I'm not entirely sure if you are asking @gvwilson to point to a person who worked on CSS for swcarpentry's repos or in general. In either case, the change that is being proposed is rather trivial.

**Comment by rgaiacs** [comment]
I mean "a person who worked on CSS for swcarpentry's repos". After we "merge" all the CSS files I lost track of them. I want to avoid that this issue appear on other websites. :-)
