### ISSUE TITLE
Is there a guide to using this repo anywhere?

### ISSUE THREAD

**Issue by ctb** [swcarpentry/styles#118]
See https://github.com/datacarpentry/python-ecology-lesson/pull/126; not sure what to do to configure things after a merge.

**Comment by ctb** [comment]
Ahh! @tracykteal pointed me at https://github.com/swcarpentry/lesson-example.

I suggest this link be placed in the "repository description" field.

**Comment by rgaiacs** [comment]
> I suggest that link be placed in the "repository description" field of this repo.

I think is done now. @ctb Could you double check and close this issue?

**Comment by ctb** [comment]
I don't see it - this is where I was looking:

<img width="653" alt="screen shot 2017-01-02 at 5 54 39 am" src="https://cloud.githubusercontent.com/assets/51016/21590360/03155cf4-d0b0-11e6-88ee-7169e4e8c165.png">

**Comment by rgaiacs** [comment]
@ctb Sorry. :-(

@jduckles @gvwilson @k8hertweck Can I get permission to fix this one or could you do address it? Thanks.

**Comment by jduckles** [comment]
Permission granted.

**Comment by rgaiacs** [comment]
@ctb Link added to the "repository description" field of this repo. Thanks.

![screenshot_2017-01-03_17-17-13](https://cloud.githubusercontent.com/assets/1506457/21616233/9dd8d6d4-d1d8-11e6-8a45-e976e0ce2faa.png)

I'm closing this now. If you have a better text to suggest let us know. :-)

**Comment by ctb** [comment]
Why multiple links in the description?

Also as long as you are asking, I would omit "no README..." as it is confusing.  (Note, if we wanted a README we could use a format/extension that doesn't conflict.)

**Comment by wking** [comment]
On Tue, Jan 03, 2017 at 09:31:03AM -0800, C. Titus Brown wrote:
> Note, if we wanted a README we could use a format/extension that
> doesn't conflict.

Or have a stub README pointing into the meat in another file.  The
stub would probably never need to be updated in this repo, so any
downstream repos would have a one-off replacement where they clobbered
the stub with their content, and there would be no further merge
conflicts.  See swcarpentry/DEPRECATED-lesson-template#215 for an
example, with README.md pointing at doc/template/ (it could also point
to doc/template/README.md or whatever).
