### ISSUE TITLE
Add max-width for images

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#13]
![screen shot 2015-02-25 at 17 31 55](https://cloud.githubusercontent.com/assets/1506457/6379684/e1dda65c-bd12-11e4-8381-89eaea7244e5.png)

**Comment by fmichonneau** [comment]
It's best to use the class "img-responsive" from bootstrap. I've added it
where I could find it but I'm sure there are many images in blog posts
where I missed it.

**Comment by r-gaia-cs** [comment]
> It's best to use the class "img-responsive" from bootstrap.

=)

> I've added it
> where I could find it but I'm sure there are many images in blog posts
> where I missed it.

Don't worry about blog posts.

**Comment by r-gaia-cs** [comment]
Duplicate of #22.
