### ISSUE TITLE
master breaks site

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#15]
![site](https://cloud.githubusercontent.com/assets/1506457/6764234/5b11f062-cf85-11e4-9ff6-1f4ebc3953e0.jpg)

**Comment by fmichonneau** [comment]
I can't reproduce this @r-gaia-cs, do you still have this issue?

**Comment by r-gaia-cs** [comment]
Sorry to forget to close this. It was fixed with f8bd46e.
