### ISSUE TITLE
lc-icon-black.svg out of sync with lc-icon-black.png

### ISSUE THREAD

**Issue by jnothman** [swcarpentry/styles#155]
`assets/img/lc-icon-black.png` is much fancier than `assets/img/lc-icon-black.svg`. The SVG is currently referenced in `_includes/carpentries.html`

**Comment by rgaiacs** [comment]
@jnothman Thanks for the report. I'm waiting Library Carpentry folks to comment.

**Comment by weaverbel** [comment]
Hey @rgaiacs I agree we should use the .png. It might be good to remove the .svg file as that was an earlier placeholder that James created before we had a proper logo and it's one we won't ever use again. Leaving it there might cause confusion. James are you happy to get that old B&W one removed? Raniere, if you could replace the image in the _includes/carpentries.html that would be great - thanks. 

@drjwbaker @jnothman

**Comment by jnothman** [comment]
The png looks like it was possibly developed in a vector graphics editor. If so it would be worthwhile to export an SVG as well.

**Comment by drjwbaker** [comment]
We appear to have lost the icon graphic from all our lessons eg http://data-lessons.github.io/library-shell/ @mkuzak was looking at it during the sprint and said something about the template change borking things and was taking a look. But not sure how far he got with it.

**Comment by rgaiacs** [comment]
> The png looks like it was possibly developed in a vector graphics editor. If so it would be worthwhile to export an SVG as well.

@drjwbaker do you have the SVG?

**Comment by drjwbaker** [comment]
Sure: [LC-logos-svg.zip](https://github.com/swcarpentry/styles/files/1127153/LC-logos-svg.zip)

**Comment by rgaiacs** [comment]
@drjwbaker Thanks.

**Comment by weaverbel** [comment]
I created an LC workshop website this week and everything including logo
rendered fine.
Belinda

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by rgaiacs** [comment]
@weaverbel the workshop is fine because it has `carpentry` at the YAML, see https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html#L4. https://github.com/swcarpentry/styles/issues/158 will require that users change the `_config`. I would remove `carpentry` from the `index.md` but someone need to patch AMY. Since AMY is out of my control I will not do the change. If you want, you can talk with @maneesha or the person in charge of AMY now to add that change to the roadmap.
