### ISSUE TITLE
Using Javascript to generate list of figures on client side

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#162]
Because all the conversation at #161 about the list of figures, here is another proposal from me.

# Background

Our authoring workflow is heavy based on GitHub Pages (Jekyll without extensions under the hood) and we are expecting that many people are going to contribute using GitHub online editor in the near future. Because of this, any page that need to be created by running a script is under optimal for our workflow. One of the pages that need to be create running a script is the "List of Figures" which use a mix of Python and Ruby. At the moment we are using client side Javascript to create the all episodes in one page version of our lessons and so far we didn't have any issue reported.

# Proposal

Replace the current "List of Figures" page with a client side Javascript generated page like the all episodes in one page.

# Benefits

- Anyone need to generate the "List of Figures" page and commit it.

# Drawbacks

- "List of Figures" will be a few seconds slow. (**not major**)

# Backward compatibility

This will not break any backward compatibility and maintainers don't need to do anything.

# Request from feedback

I would like feedback from @gvwilson as the original author of the "List of Figures".

**Comment by evanwill** [comment]
This can be done in the Jekyll project using Liquid, see my comments at #161 , which is preferable since there is no need for a client side script.

**Comment by rgaiacs** [comment]
Closed by #184.
