### ISSUE TITLE
Citing the templates?

### ISSUE THREAD

**Issue by mr-c** [swcarpentry/styles#164]
Howdy, we're using Zenodo to mint DOIs for the CWL user  guide which uses this template.

https://github.com/common-workflow-language/user_guide/issues/8

How shall we give appropriate credit to contributors to this repo? 

Perhaps a `isSupplementTo` relation to a DOI or URL to this repo?

Or some text in the `notes`?

**Comment by rgaiacs** [comment]
@k8hertweck @twitwi any recommendation?

**Comment by twitwi** [comment]
On the [zenodo]() side, it seems that `related_identifiers` could be the right place indeed but I'm not sure any of the relation conveys the proper meaning. I'm not a native English speaker, so I'm not sure about the terminology, here are the possible values:

>  (isCitedBy, cites, isSupplementTo, isSupplementedBy, isNewVersionOf, isPreviousVersionOf, isPartOf, hasPart, compiles, isCompiledBy, isIdenticalTo, isAlternateIdentifier).

My feeling is that “supplement” refers more to something like “supplementary material” for articles, and that “part” is more for “part of book or ensemble”.

A note would be probably more clear.

If we think about the generated bibtex, we'll probably have to use a note too. Related: https://github.com/swcarpentry/swc-releases/issues/4

**Comment by k8hertweck** [comment]
Not sure if you've resolved this yet or not, @mr-c, but there is a [Zenodo doi](https://zenodo.org/record/838778#.Wa60qK3Mz-Y) associated with the lesson template. Please let us know if there's anything else you need.

**Comment by mr-c** [comment]
@k8hertweck That works, thanks!
