### ISSUE TITLE
Enable syntax highlighting in Jekyll?

### ISSUE THREAD

**Issue by naught101** [swcarpentry/styles#179]
Copying from https://github.com/carpentries/instructor-training/issues/543

As noted at https://github.com/carpentries/instructor-training/pull/536, when using the language-specific code block notation, syntax highlighting is not enabled. I'm not sure if this is intentional or not, but I think syntax highlighting vastly improves code readability, and would be great to have in this course.

I am happy to figure out how to enable this, and create a PR if others thing that's a good idea, but it would be good to know beforehand whether any work has been done on this, or if there's a reason why it's not already the case.

**Comment by rgaiacs** [comment]
Syntax highlight is disabled. Instructor agreed that syntax highlight could disturb learners for different reasons including question why their text editor is colouring something with X when the lesson uses Y. In addition to that, because we also had agreed that our lessons should be accessible/disabled friendly I'm strong against add syntax highlight.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristinaLK** [comment]
I think that syntax highlighting would improve readability -- even if the colors were different from what a learner was seeing.  They shouldn't necessarily be reading the lesson while in the workshop anyway.  

For the accessibility question, is that we don't want to add a feature (in this case, syntax highlighting) to the lesson if it's not available for everyone?

**Comment by rgaiacs** [comment]
> is it that we don't want to add a feature (in this case, syntax highlighting) to the lesson if it's not available for everyone?

I need to make a distinction between "not available for everyone" and "deteriorate the experience for someone". I'm not against a feature that is not available for everyone, for example, Firefox and Chrome behave different sometimes so I would probably say +1 for a nice feature only available in one web browser but not in others (I wanted to use `<details>` and `<summary>` when it wasn't available in Firefox). I'm strong against any feature that we know that can (or will) deteriorate the experience for someone because this make us not friendly with a specific group (probably a minority).

Someone said

>  I can't see how syntax highlighting via color would be in any other way any sort of accessibility issue.

in [StackExchange](https://ux.stackexchange.com/a/40355). I will retract my original position as long as someone with experience in accessibility can pick a color palette because I don't feel competent to make the selection.

**Comment by gcapes** [comment]
I don't feel in a position to comment on accessibility, but avoiding syntax highlighting on the grounds that it might look different to a learner's editor doesn't seem to hold much water. By turning syntax highlighting off, our lessons probably already look different to most learners' editors, and more so than if the highlighting used a different colour scheme for example.

So I'm generally in favour of syntax highlighting.

**Comment by naught101** [comment]
@rgaiacs: as pointed out in unor's answer on that post, syntax highlighting shouldn't affect accessibility. It should not be read aloud by screen-readers, since it doesn't affect the content. For the colour blind, it also shouldn't make things *worse*, because even if two colours are indistinguishable, there are still more colours visible than if it's all just black-on-white (but ideally a colour-blindness friendly scheme should be used anyway). For users with general poor vision, as long as the high contrast is maintained, colour should help convey meaning, and not hinder it.

On the other hand, for anyone not familiar with coding (which is most people at an SC workshop, presumably), it provides an immediate improvement in accessibility (in the familiarity sense), because there are visual aids in deciphering what all of the symbols mean. So it should lead to fewer syntax mistakes.

**Comment by rgaiacs** [comment]
@naught101 as I said, I don't want to pick the color palette. Pull request from someone with experience would be great.

**Comment by ChristinaLK** [comment]
Okay, so syntax highlighting is a go, we just need to make sure the colors used are accessible (re: color blindness).  @rgaiacs , I don't think we need someone w/ specific experience in this area as long as the colors are checked via something like https://www.toptal.com/designers/colorfilter or another online tool.  @naught101, I'd say that you can take this on if you want!

**Comment by naught101** [comment]
The "default" [pygments style](https://richleland.github.io/pygments-css/) is Blue/green.

![screenshot_20171109_111440](https://user-images.githubusercontent.com/167164/32581761-73b9a2ba-c53f-11e7-862f-2632e005cabe.png)

I've run it through the simulator at http://www.color-blindness.com/coblis-color-blindness-simulator/, and it looks perfectly useful for everyone. The colours are not very distinct for Blue-blind users  (objects and keywords look similar in python), but the highlighting is still useful, I think, and definitely not worse than no highlighting:

![canvas](https://user-images.githubusercontent.com/167164/32581824-c6379538-c53f-11e7-87ac-4792002b5718.png)

The style is also minimal, and will work reasonably well with the current SWC colour theme.

**Comment by rgaiacs** [comment]
@naught101 Thanks for your investigation. GitHub Pages uses [rouge](https://github.com/jneen/rouge). Could you have a look at what we need to change? If you send a pull request to https://github.com/swcarpentry/lesson-example with the changes enabling syntax highlighting I can pick from there and do the rest (send a pull request to this repo, merge, merge this repo into https://github.com/swcarpentry/lesson-example, send a pull request to https://github.com/swcarpentry/lesson-example, ...). Thanks in advance.

**Comment by naught101** [comment]
Trying to get that repo up and running, and I'm hitting this problem: https://github.com/swcarpentry/lesson-example/issues/143, so it's a bit hard to test at the moment.

**Comment by rgaiacs** [comment]
@naught101 Thanks for your help. Please see https://github.com/swcarpentry/lesson-example/issues/143#issuecomment-343656689.

**Comment by naught101** [comment]
Created a pull request at https://github.com/swcarpentry/lesson-example/pull/144, but there's a stumbling block - it doesn't work with the existing formats (explained over there).

**Comment by rgaiacs** [comment]
This was implemented. Thanks @naught101.
