### ISSUE TITLE
Page build failure upon importing styles repo

### ISSUE THREAD

**Issue by DamienIrving** [swcarpentry/styles#191]
I imported the styles repo (see https://github.com/DamienIrving/pyaos-lesson) and immediately received the following email from GItHub.

---------- Forwarded message ----------
From: GitHub <support@github.com>
Date: Tue, Nov 14, 2017 at 3:25 PM
Subject: [DamienIrving/pyaos-lesson] Page build failure
To: Damien Irving <irving.damien@gmail.com>

The page build failed for the `gh-pages` branch with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by rgaiacs** [comment]
@DamienIrving Thanks for the report.

GitHub Pages was to be disabled for this repository. I try to turn it of but couldn't.

![screenshot from 2017-11-14 09-44-10](https://user-images.githubusercontent.com/1506457/32773292-9da60cd2-c920-11e7-8a82-71039016e4b6.png)

This could be a permission issue. I will have a deep look later.

**Comment by rgaiacs** [comment]
@DamienIrving Thanks again for the report. I don't remember why we was using gh-pages for this repo if we wasn't publishing any page. I renamed the `gh-pages` branch to `master` and removed the `gh-pages` branch so GitHub Pages will not try to build anything. Sorry for the trouble.

**Comment by DamienIrving** [comment]
Thanks, @rgaiacs. Now that the `gh-pages` branch is gone, does something else need to be done in order for `https://timtomch.github.io/data-cleanup` to go live? When I use the importer to import the updated styles repo no website is generated...

**Comment by rgaiacs** [comment]
OK. You make me realise that I did a mistake with the branches. I will write about it tomorrow.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rgaiacs** [comment]
@DamienIrving, I created the `gh-pages` branch and removed the `master` one. Sorry for all the trouble.

**Comment by DamienIrving** [comment]
@rgaiacs - Sorry to be a pest, but now we are back to the original problem. When I import the styles repo (see https://github.com/DamienIrving/pyaos-lesson), I immediately get a page build failure email.

**Comment by DamienIrving** [comment]
@rgaiacs Nevermind! Sorry. I needed to read the instructions at http://swcarpentry.github.io/lesson-example/setup.html better!
