### ISSUE TITLE
Preserve history from lesson-template?

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#2]
@gvwilson Do you want the history of CSS from lesson-template preserved?

**Comment by gvwilson** [comment]
If it's easy to do, then yes.  If it's going to take more than a few 
minutes, then no, I don't think it's worth it.

**Comment by fmichonneau** [comment]
I don't know how to get the past history of the CSS. Raniere (or someone
else), if you know how/want to do it, you could populate the repository
with it. Otherwise, I'll just push what I have now. Thanks.

**Comment by r-gaia-cs** [comment]
I populated the repository based on https://github.com/swcarpentry/bc.

@fmichonneau and @jpallen Could you please cherry-pick the work that you did in the past few days? Thanks a lot.
