### ISSUE TITLE
Improve layout for figure caption

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#21]
Isn't clear what is the caption and the text.

![fig](https://cloud.githubusercontent.com/assets/1506457/6789931/c0479032-d182-11e4-9e06-8274625c6277.jpg)

Need a layout for

~~~
$ pandoc <<EOF
![foo](bar.jpg)  
heredoc> EOF
<div class="figure">
<img src="bar.jpg" alt="foo" />
<p class="caption">foo</p>
</div>
~~~

that are compatible with

~~~
$ pandoc -t html5 <<EOF
![foo](bar.jpg)
EOF
<figure>
<img src="bar.jpg" alt="foo" /><figcaption>foo</figcaption>
</figure>
~~~

**Comment by fmichonneau** [comment]
maybe, we could use the caption class from bootstrap: http://getbootstrap.com/components/#thumbnails-custom-content
