### ISSUE TITLE
Trademark need update

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#211]
The trademark in https://github.com/swcarpentry/styles/blob/gh-pages/LICENSE.md and the copy of this files in **all** lessons plus workshop-template repository need update.

# Reasoning

As mentioned [here](https://software-carpentry.org/blog/2018/01/fiscal-sponsor-transition.html),

> As part of this transition, Software Carpentry and Data Carpentry are moving from Fiscally Sponsored Projects with NumFOCUS to The Carpentries with Community Initiatives

# How should it be?

https://github.com/swcarpentry/styles/blob/gh-pages/LICENSE.md should state

> # Trademark
>
> "Software Carpentry" and "Data Carpentry" and their respective logos are registered trademarks of Community Initiatives.

# How is it now?

> # Trademark
>
> "Software Carpentry" and "Data Carpentry" and their respective logos are registered trademarks of NumFOCUS.

# How to fix

1. Change the `LICENSE.md` file.
2. Run https://github.com/swcarpentry/infra-lessons.

@fmichonneau or @ErinBecker, Could you fix this?

**Comment by fmichonneau** [comment]
I am happy to do this. @tracykteal or @jduckles could you please confirm that the text suggested by Raniere is accurate?

**Comment by jduckles** [comment]
I fixed this on all SWC lessons by hand yesterday with the following:
```
"Software Carpentry" and "Data Carpentry" and their respective logos
are registered trademarks of [Community Initiatives][CI].

[cc-by-human]: https://creativecommons.org/licenses/by/4.0/
[cc-by-legal]: https://creativecommons.org/licenses/by/4.0/legalcode
[mit-license]: http://opensource.org/licenses/mit-license.html
[ci]: http://communityin.org/
[osi]: http://opensource.org
```
Didn't know there was automation magic for the licenses. So I think for SWC if we just fix this upstream we'll be good going forward.

**Comment by jduckles** [comment]
Counting the lessons in the `infra-lessons` script. I only did this to 11 lessons. So you can run it again to catch the 12th one I missed.
