### ISSUE TITLE
Can we add max-width for img?

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#22]
![img](https://cloud.githubusercontent.com/assets/1506457/6789954/f22f9b30-d182-11e4-8c14-37101eedd899.jpg)

**Comment by fmichonneau** [comment]
it's best to use the class "img-responsive" from bootstrap in this case. Not only it will avoid images to get wider than the container but it also looks good regardless of the resolution. Could we add it when the pages are being built from the markdown files?

**Comment by r-gaia-cs** [comment]
> it's best to use the class "img-responsive" from bootstrap in this case.

+1

> Could we add it when the pages are being built from the markdown files?

Probably yes. I will look for it.
