### ISSUE TITLE
switch all code in this repo to python3.4

### ISSUE THREAD

**Issue by mr-c** [swcarpentry/styles#232]
For simplified maintenance.

Python3.3 and earlier have already reached end of life: https://devguide.python.org/#status-of-python-branches

Python3 is the version of software carpentry that is taught.

I'm happy to send a PR if this is agreed upon.

- [ ] bin/repo_check.py
- [ ] bin/lesson_initialize.py
- [ ] bin/workshop_check.py
- [ ] bin/util.py
- [ ] bin/test_lesson_check.py
- [ ] bin/lesson_check.py
- [ ] update https://github.com/swcarpentry/lesson-example/blob/gh-pages/setup.md https://github.com/swcarpentry/lesson-example/pull/198

**Comment by rgaiacs** [comment]
> I'm happy to send a PR if this is agreed upon.

Any pull request will be great.
