### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#233]
See https://github.com/swcarpentry/python-novice-inflammation/pull/502.

**Comment by alee** [comment]
Should we still be targeting Python 2.7? If so it would be good to test Python 3 versions as well, either by [including them in the .travis.yml python section](https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions) or adding [tox](https://tox.readthedocs.io/en/latest/).

**Comment by mr-c** [comment]
I advocate for just Python 3.

**Comment by maxim-belkin** [comment]
1. The reason I used Python 2.7 in Travis config file is because standard `Makefile` in swc repos executes `bin/lesson_check.py` which calls `python` (`#!/usr/bin/env python` shebang).

2. There is no need in using multiple Python versions in CI. 

Also, be sure to add
```
branches:
  only:
  - gh-pages
  - /.*/
```
because Travis ignores `gh-pages` branches by default.
swcarpentry/python-novice-inflammation#507

**Comment by alee** [comment]
thanks for the reminder maxim - this is a larger issue but perhaps we should be using the `master` branch for source material and `gh-pages` for generated static files like the rest of github. At the moment it's fairly innocuous but I see it as [contagious technical debt](https://engineering.riotgames.com/news/taxonomy-tech-debt) that's counter to most published docs & convention and will require these types of workarounds into perpetuity.

travis symlinks /usr/bin/python to python3 if you specify python 3 so if you used python 3.6 the Makefile should still run fine.

**Comment by maxim-belkin** [comment]
> perhaps we should be using the master branch for source material and gh-pages for generated static files like the rest of github

I couldn't agree more :)

> travis symlinks /usr/bin/python to python3

Well, this is not a common practice so if we're talking about reproducibility, we should be enforcing it :)

**Comment by rgaiacs** [comment]
Done in swcarpentry/styles#260
