### ISSUE TITLE
Some text missing

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/styles#245]
Just before Point 7 in `setup.html`, there is a sentence that just ends `and` with no further info or full stop after it and then it goes straight on to the point. Can this be right?

**Comment by rgaiacs** [comment]
> Just before Point 7 in setup.html

We don't have Point 7 in https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py#L270. I'm closing this and reopening https://github.com/swcarpentry/lesson-example/issues/200.
