### ISSUE TITLE
Search does not search within the site

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/styles#246]
I think the search box is not working as it should.

When searching for `something`, the search URL is:

```https://www.google.com/search?q=something+site:```

I think it missing the `domain` part in this function:

```js
function google_search() {
  var query = document.getElementById("google-search").value;
  var domain = $("meta[name=search-domain]").attr("value");
  window.open("https://www.google.com/search?q=" + query + "+site:" + domain);
}
```

**Comment by rgaiacs** [comment]
@iglpdc Thanks for the issue. I fixed it on this repository and patch any lesson repository should only require a merge from this repository.
