### ISSUE TITLE
"Waiting for contributor response" label

### ISSUE THREAD

**Issue by maxim-belkin** [swcarpentry/styles#474]
I'd like to propose to add a "Waiting for user response" or "Waiting for user to respond" label. I think it could be useful for maintainers.

-- Added on July 23, 2020

I also suggest adding a label for style/formatting-related issues and PRs (https://github.com/carpentries/styles/issues/474#issuecomment-663038386)

And for this repository, changes can be github-related and lesson-template related, so, perhaps, it would be worth adding:

"GitHub-related issue" label

**Comment by brownsarahm** [comment]
we should use "contributor" instead of "user" to be consistent with the language on the status:changes requested label.

**Comment by maxim-belkin** [comment]
Yes, "Waiting for Contributor response" makes more sense.

**Comment by maxim-belkin** [comment]
I also suggest adding a "Fix lesson style/formatting" or "type: fix style/formatting" label.

**Comment by brownsarahm** [comment]
I would prefer using only "formatting" or possibly "syntax" to differentiate when the issue should be opened against this repo (`carpentries/styles`) instead of a lesson, but I agree that would be a helpful label. 

I like the "type:" prefix

**Comment by fmichonneau** [comment]
Would you be willing to open a PR against this CSV file that we use to update our labels across our repositories?

**Comment by maxim-belkin** [comment]
Where can I find that CSV? :)

**Comment by fmichonneau** [comment]
here is it! https://github.com/carpentries/docs.carpentries.org/blob/master/data/github_labels.csv

**Comment by maxim-belkin** [comment]
Thank you!

**Comment by maxim-belkin** [comment]
Resolved in carpentries/docs.carpentries.org#668 🎉
