### ISSUE TITLE
use {renv} to create local library of packages for each lesson

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/styles#499]
using {renv} would allow us to create independent libraries for each lesson, and therefore we wouldn't need to touch the maintainers/contributors personal installation. The lesson scripts could continue to rely on always using the latest versions of the packages (or pinned ones if that was needed) without interferring with what people building the lessons want to do with their versions.

**Comment by zkamvar** [comment]
Note that {renv} by default will use the pinned versions, so we would need to come up with a way to test and update the lock file.

**Comment by fmichonneau** [comment]
this is implemented in {sandpaper}

**Comment by zkamvar** [comment]
Note, this was first implemented in sandpaper version 0.0.0.9050: https://github.com/carpentries/sandpaper/pull/158

Technical reference: https://carpentries.github.io/sandpaper/articles/building-with-renv.html
