### ISSUE TITLE
Github import fails

### ISSUE THREAD

**Issue by ewallace** [swcarpentry/styles#505]
I am having a failure for this repository on github import, which means that I can't follow the lesson setup instructions in [lesson-example setup](https://carpentries.github.io/lesson-example/setup.html).

I follow the instructions, and get the github error message:

> We found an error during import
> We recommend restarting the import process, but if you are still having trouble contact support.
> There was an error pushing commits to GitHub.

[The repository is created with a `README.md` and 18 tags](/ewallace/test_styles).

I've tried this several times, including after deleting the new erroneous repository, and also with a different name. Both to my account and to [@edcarp](/edcarp). Always with the same result.

I raised the issue with github, ticket [851404](https://support.github.com/ticket/personal/0/851404), nothing useful yet.

Any ideas how to fix?

**Comment by maxim-belkin** [comment]
This does sound like a GitHub problem.

You can mimick GitHub import with the following steps:
1. Create an empty repo on GitHub (don't initialize any files)
2. Clone carpentries/styles repo to your computer.
3. Change the remote `origin` to point to the empty repo created in step 1
4. Push cloned repo to the empty repo

```
# 1. https://github.com/new -- Create an empty repo on GitHub, say <username>/<mylesson>
git clone https://github.com/carpentries/styles.git /some/folder/on/your/computer
cd  /some/folder/on/your/computer
git remote set-url origin https://github.com/<username>/<mylesson>.git
git push origin gh-pages
```

**Comment by brownsarahm** [comment]
I was able to recreate this issue, the import is not currently working. I had an issue with my materials for my course a few weeks ago where import stopped working, but there was something in the repo that I changed and fixed it.  I can look back tomorrow maybe to try to remember what I did and fixed, but if anything structural changed here recently, that could also be the culprit. 

We wouldn't want whatever the issue here is to propagate into the workshop website template that we need the template functionality to work for.

**Comment by ewallace** [comment]
I've written some instructions to fix, as suggested by @maxim-belkin, in [lesson-example#301](/carpentries/lesson-example/pull/301). Would you mind taking a look at it?

**Comment by sstevens2** [comment]
Reporting that this is still an issue and I'll do the local work around.

**Comment by fmichonneau** [comment]
instructions on how to use the command line to replicate what the importer does have been added to the lesson example repo.
