### ISSUE TITLE
Mark carpentries/styles repository as a Template repository

### ISSUE THREAD

**Issue by maxim-belkin** [swcarpentry/styles#518]
I propose to mark this repository as a Template repository so that others can click "Use this template" (or navigate to https://github.com/carpentries/styles/generate) to get started with lesson development

<details>
<summary>Checkbox location</summary>

![image](https://user-images.githubusercontent.com/13123663/98855360-7c212600-2421-11eb-81d0-718f9409fa74.png)
</details>

**Comment by fmichonneau** [comment]
done. We'd need to check what default branch is enabled after using the feature though, and if it's not `gh-pages` we'd need to add this clearly in the documentation.

**Comment by fmichonneau** [comment]
I just tested and `gh-pages` is the default and only branch :confetti_ball:

**Comment by zkamvar** [comment]
Will this affect the update process for new repos? I seem to recall some discussion (though I can't find where) about using this feature and the fact that it would start with no commit history, which would mean that you can't create a pull request from the styles repo because there is no shared history.

**Comment by maxim-belkin** [comment]
You're correct, Zhian. Template repositories start with all the repository content packed into a single "Initial commit" and I don't see a way to preserve repo history on the /generate page. I haven't noticed that initially, so thanks for the info.

@fmichonneau, unfortunately it looks like we have to undo this change and document why we can't use it. Sorry for the trouble.

**Comment by fmichonneau** [comment]
Thanks Zhian! I only remembered the issue of the lack of Git history a few hours after enabling this. I'm reverting it now.
