### ISSUE TITLE
Color scheme for links

### ISSUE THREAD

**Issue by bkmgit** [swcarpentry/styles#525]
Make links appear in a color that has better contrast to the default black text. It may also be helpful to have links underlined or possibly in bold. This is particularly helpful for the links in the setup instructions which may be initially read by participants without much guidance.

**Comment by brownsarahm** [comment]
@bkmgit I've moved this issue to a different repository where we maintain the styling of the lessons separately from the 
example. 

Thanks for pointing this out, it's related to an open pull request #511 Feel free to comment if that does or does not address all of your concerns.

**Comment by bkmgit** [comment]
Thanks #511  and #549 seem to address this.
