### ISSUE TITLE
lesson_check.py --permissive for pre-alpha?

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/styles#533]
I'm not so familiar with what's possible in GNU Make or GitHub Actions. Could the Makefile be adjusted such that the `lesson_check` script is run with the `--permissive` option for lessons in `pre-alpha`? Or adjust `.github/workflows/website.yml` to achieve the same for pull requests/commits made while in pre-alpha? Or is this kind of querying of the `_config.yml` not really possible in this context?

**Comment by zkamvar** [comment]
If it's specific for pre-alpha, I think it would be better to engineer `lesson_check.py` to auto-apply the permissive flag for pre-alpha versions. Neither Make or GHA really care about the contents of any files.

**Comment by ErinBecker** [comment]
@allendowney - Just wanted to send you a heads up that this should fix some of the problems you've been experiencing with the Astronomy lesson. Thank you for reporting the issue!

**Comment by AllenDowney** [comment]
@ErinBecker Great, thanks!
