### ISSUE TITLE
Add a Readme

### ISSUE THREAD

**Issue by baileythegreen** [swcarpentry/styles#574]
to this repo because the single sentence in its description does not provide enough information to make up for the ambiguous name of the repo.

Ideally, the Readme would include some detailed explanation of how this repo differs in its intended use from https://github.com/carpentries/carpentries-theme, given that Jekyll themes are basically rules for styling pages.

I am not able to propose a suitable Readme in a PR myself because I do not completely understand the purpose of this repo....

**Comment by fmichonneau** [comment]
I think we can't have a README for this repo because it would lead to confusing merge conflicts when updating the template in the lesson repositories.

**Comment by baileythegreen** [comment]
Could that be solved by adding the Readme to `.gitignore`?

If not, can the description be expanded, at least?

**Comment by maxim-belkin** [comment]
> because I do not completely understand the purpose of this repo....

This repo is the backbone of The Carpentries lessons -- navigation bar, icons, stylesheets, etc. The Carpentries lessons use Jekyll / GitHub pages, so without this repo one would have to set up all the styles manually and every lesson would look different. 

This repo is mentioned in the [Lesson Example](https://carpentries.github.io/lesson-example/setup.html#creating-a-new-lesson) and in the Curriculum Development Handbook - [1](https://carpentries.github.io/curriculum-development/the-lesson-life-cycle.html#early-development-pre-alpha-through-alpha), [2](https://carpentries.github.io/curriculum-development/technological-introductions.html#using-the-lesson-template). 

> Could that be solved by adding the Readme to `.gitignore`?

No. `.gitignore` file  tells Git to not include specified files in the repository. This (usually) means that if a file is listed in `.gitignore`, you won't see it on GitHub (well, unless you `add --force` that file).

> If not, can the description be expanded, at least?

Text in the description box used to say something else: my fork -- https://github.com/maxim-belkin/styles -- has the following wording in it: `Styles for SWC/DC sites: no README to avoid merge conflicts w/ those repos.` Raniere Silva's fork -- https://github.com/rgaiacs/swc-styles -- says `CSS and other style material shared across multiple sites`.  Perhaps, something like `Styles for The Carpentries lessons. No README to avoid merge conflicts with lessons.` would be better?

**Comment by maxim-belkin** [comment]
The description has been updated.
