### ISSUE TITLE
Allow blank lines and comments when checking `links.md`

### ISSUE THREAD

**Issue by jhlegarreta** [swcarpentry/styles#581]
The `make lesson-check-all` script seems not to allow blank lines and comments in the `links.md` file according to the following report in a `carpentries-incubator` repository:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/142/checks?check_run_id=2400917706#step:16:9

Removing the blank lines and comments in the relevant file:
https://raw.githubusercontent.com/carpentries-incubator/SDC-BIDS-dMRI/master/_includes/links.md

Allows the script to complete its checks about the file naming style, line length, etc.

We introduced blank lines and comments in the `links.md` file to make a clear distinction between the links belonging to the carpentries ecosystem and those specific to the lesson.

I ignore whether this impacts other Markdown files of the carpentries ecosystem.

I'd say that the [`lesson-check.py`](https://github.com/carpentries/styles/blob/gh-pages/bin/lesson_check.py) called by `lesson-check-all` should allow blank lines and comments in the concerned Markdown files as long as it is a valid Markdown comment.

Thanks for such a great tool to check the consistency of a given lesson to the carpentries style.

**Comment by jhlegarreta** [comment]
@maxim-belkin Looks like the described behavior is not observed in other PRs:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/2401702149?check_suite_focus=true

Not sure why.

**Comment by maxim-belkin** [comment]
@jhlegarreta, not sure why some runs fail and other don't for you -- don't have the time to look into this at the moment.

just an FYI: the `links.md` file is not supposed to be edited in the individual lessons but in this repository only. This file includes links that are used by all lessons. It might not be a bad idea to add another file (e.g. `lesson_links.md`) and `{% include ... %}` it in `links.md`

**Comment by jhlegarreta** [comment]
> just an FYI: the links.md file is not supposed to be edited in the individual lessons but in this repository only. This file includes links that are used by all lessons. It might not be a bad idea to add another file (e.g. lesson_links.md) and {% include ... %} it in links.md

:+1: sounds reasonable. We'll give a try to splitting the links into two files.
