### ISSUE TITLE
Broken link in Boilerplate Contributing.md

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/styles#609]
One of our contributors caught a broken link in the contributing.md page. 
https://github.com/swcarpentry/git-novice/issues/783

**Comment by maxim-belkin** [comment]
Thanks, @kekoziar. Would you like to submit a PR to fix it?

**Comment by kekoziar** [comment]
Done, @maxim-belkin.  Thanks!

**Comment by maxim-belkin** [comment]
Fixed in https://github.com/carpentries/styles/commit/6b49768a34a85f1d39d521d57ecfe6ad053b2de0
