### ISSUE TITLE
Encoding error when trying to serve a jekyll project

### ISSUE THREAD

**Issue by GuillermoFidalgo** [swcarpentry/styles#629]
Hello, I'm having an issue when trying to serve a project (In my case it's https://github.com/GuillermoFidalgo/hsf-training-matplotlib)
I get the following

```shell
guillermofidalgo@Guillermos-MacBook-Pro hsf-training-matplotlib % bundle exec jekyll serve
Configuration file: /Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib/_config.yml
            Source: /Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib
       Destination: /Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
jekyll 3.9.0 | Error:  Invalid US-ASCII character "\xE2" on line 5
/Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib/.vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid US-ASCII character "\\xE2" on line 5 (Jekyll::Converters::Scss::SyntaxError)

```

(A bunch of output)

```shell
from /Users/guillermofidalgo/.gem/ruby/3.0.0/gems/bundler-2.2.29/exe/bundle:37:in `<top (required)>'
	from /Users/guillermofidalgo/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /Users/guillermofidalgo/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
/Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib/.vendor/bundle/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_sass/primer-support/lib/variables/typography.scss:5: Invalid US-ASCII character "\\xE2" (Sass::SyntaxError)
```

(Some more lines)

```shell
/Users/guillermofidalgo/Documents/Websites/hsf-training-matplotlib/.vendor/bundle/ruby/3.0.0/gems/sass-3.7.4/lib/sass/util.rb:1088:in `encode': "\\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII (Encoding::UndefinedConversionError)

```
(you get the idea)

I'm wondering if anyone has had this issue before and how I could go about solving this?\

I've tried reinstalling jekyll and ruby but does not seem to change anything.

I've reinstalled the gems and no luck.
Any ideas?

**Comment by maxim-belkin** [comment]
> ```shell
> Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
>                     Invalid US-ASCII character "\xE2" on line 5
> jekyll 3.9.0 | Error:  Invalid US-ASCII character "\xE2" on line 5
> ```

I think Jekyll complains about `style.scss` file that you added to `assets/css` directory -- check its line 5 or delete it, if you don't need it.

**Comment by maxim-belkin** [comment]
`\xe2` is most likely a "smart quotation mark" that should be replaced with `'`

**Comment by GuillermoFidalgo** [comment]
There is no `style.scss` here. I'm not sure if this means that it's looking somewhere else.

```shell
guillermofidalgo@Guillermos-MacBook-Pro hsf-training-matplotlib % ls -ahltr assets/css/
total 1296
-rw-r--r--  1 guillermofidalgo  staff    25K Oct 18 12:42 bootstrap-theme.css
-rw-r--r--  1 guillermofidalgo  staff    47K Oct 18 12:42 bootstrap-theme.css.map
-rw-r--r--  1 guillermofidalgo  staff   143K Oct 18 12:42 bootstrap.css
-rw-r--r--  1 guillermofidalgo  staff   382K Oct 18 12:42 bootstrap.css.map
-rw-r--r--  1 guillermofidalgo  staff    23K Oct 18 12:42 katex.min.css
-rw-r--r--  1 guillermofidalgo  staff    10K Oct 18 12:42 lesson.scss
drwxr-xr-x  9 guillermofidalgo  staff   288B Oct 18 12:42 ./
-rw-r--r--  1 guillermofidalgo  staff   4.3K Oct 18 12:42 syntax.css
drwxr-xr-x  7 guillermofidalgo  staff   224B Oct 18 12:42 ../

```

**Comment by maxim-belkin** [comment]
I cloned your lesson and was able to build/serve a website without an issue. A few things to try:
1. `make clean` then `make serve`
2. Do you have `LC_ALL` and/or `LANG` set? What does `locale charmap` return?

**Comment by GuillermoFidalgo** [comment]
1. Resulted in same issue as before
2. I get 
```
$ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

$ locale charmap
US-ASCII

```

**Comment by maxim-belkin** [comment]
Try setting `LANG` to `something.UTF-8`. For example, in my case I have `en_US.UTF-8`.

**Comment by maxim-belkin** [comment]
If changing `LANG` doesn't help, try setting `LC_ALL` (to `en_US.UTF-8` or anything else.UTF-8) instead.

**Comment by GuillermoFidalgo** [comment]
Changing `LANG` worked 😄 
Thank you so much! I think I know why this was not set or changed.
Some time ago I was trying to install a package on a remote machine and it used to complain about `ascii` encoding. 
Following a few forum posts I ended up unchecking the setting on the Mac terminal under "Advanced" that says "Set locale enviroment variables on startup".

That fixed my issue back then but must have brought up this issue now.
Thanks again!

**Comment by maxim-belkin** [comment]
Thanks for the report, @GuillermoFidalgo. I think this is something we might want to tackle in the Makefile. By the way, I would recommend using `make serve` and `make site` instead of invoking Bundler directly.

**Comment by GuillermoFidalgo** [comment]
Thanks for the tip. I did it both ways and same output arose. I just happened to paste it with bundler here
