### ISSUE TITLE
should this repo also include SWC logos?

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/styles#7]
Following @wking's suggestion in swcarpentry/workshop-template#152, it seems that we need to discuss whether the SWC logos should be included in this repository.

Currently, the workshop template gets the logo from software-carpentry.org, while the logo is included in the repository for lesson templates and the main website. 

Having them in a single location would limit duplication, allow for offline rendering of the workshop templates, and facilitates serving over https. If we decide to go this way, we will probably need to create a new directory that will only contain images shared across all sites.

**Comment by iglpdc** [comment]
There is a new repo in the making, [swcarpentry/communications](https://github.com/swcarpentry/communications), aimed to centralize our external communications, from boilerplates for grant proposals to templates to announce workshops. The materials there will need also the SWC logos and other graphical stuff.

So, +1 to centralized all the graphics in just one place, whichever the technical solution be chosen.

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 08:32:32AM -0800, Ivan Gonzalez wrote:
> There is a new repo in the making, swcarpentry/communications, aimed
> to centralize our external communications, from boilerplates for
> grant proposals to templates to announce workshops. The materials
> there will need also the SWC logos and other graphical stuff.
> 
> So, +1 to centralized all the graphics in just one place, whichever
> the technical solution be chosen.

It looks like we have a few other images that I think we should also
keep in this repository:

  $ git --no-pager grep '[.]png'
  css/slideshow.css:  background: url(../img/software-carpentry-banner.png) bottom 10px left 10px no-repeat;
  css/swc.css:  list-style-image: url('../img/checkbox.png');
  css/swc.css:    background: url(../img/header.png) no-repeat center center;
  css/swc.css:    background:url('../img/software-carpentry-banner-white.png') no-repeat;
  css/swc.css:    background: url("/img/main_shadow.png") repeat-x scroll center top #FFFFFF;
  $ find . -name 'img'
  … no results …

I don't mind if we also want to store the logo in
swcarpentry/communications, but I'd rather keep the content referenced
from these style sheets in this repository.  The material is unlikely
to change often, so duplication between swcarpentry/styles and
swcarpentry/communications wouldn't be too terrible.

In any case, it looks like we're *already* using local links here, so
my comment in swcarpentry/workshop-template#152 was a bit off-base.

**Comment by DanielBaird** [comment]
So, will the CSS from here be moved into the communications, into a directory called something like website-assets or website-boilerplate maybe?
