### ISSUE TITLE
Prev/Next arrows at the bottom of episodes as well as the top?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/styles#78]
@orchid00 recommends prev/next links at the bottom of lesson episodes as well as the top. My attempts to style this have all been exceptionally ugly - a PR would be welcome. (You can test your PR by making changes in a local copy of https://github.com/swcarpentry/lesson-example and previewing with `make serve` (or pushing to your own gh-pages branch).)

**Comment by rgaiacs** [comment]
I believe this is implemented now.
