### ISSUE TITLE
Use 00:00 as a default start time for lessons

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/styles#79]
Lessons currently use 09:00 as a start time for the schedule - @jduckles suggests using 00:00 (to show elapsed time). This makes sense for half-day lessons, but it's helpful with full-day lessons to show where the lunch break comes (12:00 is more easily understood than 03:00). Preferences?

**Comment by gdevenyi** [comment]
+1 for adjusting to elapsed time.

Does it make sense perhaps to allow somewhere to set a "start time" variable that allows computation of the real time?

**Comment by gvwilson** [comment]
`start_time` can be set in `_config.yml`, but I don't see how to adjust 
on a workshop-by-workshop basis without cloning the lesson repo per 
workshop.

**Comment by gdevenyi** [comment]
Hrm, I seem to recall that being a recommended step that the lessons be forked off for a given workshop so that the lessons don't change during use?

**Comment by iglpdc** [comment]
I prefer a "sensible" start time, like 9:00 am or noon. I think it's easier to track time during the lesson with that. 

Also a minor point. I think the timing is useful only for instructors when preparing the lesson and that the ideal place for that would be the instructor's guide. The index page could show not the schedule, but the syllabus (the same without the timing column). 

The reason I'm saying this is that lessons during workshops usually don't go as expected, so putting very precise times so upfront may put extra pressure on novices instructors and create false expectations on learners.

**Comment by tbekolay** [comment]
I think as we do it now, elapsed time (starting at 00:00) makes more sense. If we were to explicitly add in a lunch break for full-day lessons (at noon) then I would favor the 09:00 start time.

**Comment by hdashnow** [comment]
+1 for starting at 00:00, and would like an additional column for time for each lesson.

I think time estimates starting at 9:00 would make more sense for the individual workshop pages, so the instructor can explicitly set the break times etc. Not necessary, in my opinion. But if you were keen on the idea and wanted to put it somewhere...

**Comment by naupaka** [comment]
I like elapsed time as well. Some workshops start at 8:00 or 8:30 instead of 9:00...

**Comment by gvwilson** [comment]
Looks like 00:00 is the favored option - individual lessons can always switch it.  (I can't find any way to adjust the lesson timings per workshop without cloning the repo for each workshop.)
