### ISSUE TITLE
bin/util.py fails to run if user has python 2.7 as system default

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/styles#84]
Perhaps worth adding a check for python version? Not a python guru myself so not sure best way to handle this. Or maybe I just missed something somewhere. But it looks like a python 3 `print()` call is gumming things up.

Noticed because `make lesson-check` was failing for me.

``` python
make lesson-check                                                                                   
Traceback (most recent call last):
  File "bin/lesson_check.py", line 14, in <module>
    from util import Reporter, read_markdown, load_yaml, check_unwanted_files, require, IMAGE_FILE_SUFFIX
  File "/Users/naupaka/git/Software_Carpentry/r-novice-gapminder/bin/util.py", line 10
    print('Unable to import YAML module: please install PyYAML', file=sys.stderr)
                                                                     ^
SyntaxError: invalid syntax
make: *** [lesson-check] Error 1
```

Isolated to the script:

``` python
python bin/util.py                                                                                  
  File "bin/util.py", line 10
    print('Unable to import YAML module: please install PyYAML', file=sys.stderr)
                                                                     ^
SyntaxError: invalid syntax
```

No problem with python3.

```python
python3 bin/util.py
<<no output>>
```

**Comment by gdevenyi** [comment]
Problem is the "future" version of the print function, that function is available in python2 as a future import, see #85 for a fix.

**Comment by gvwilson** [comment]
Alternatively, can we modify the `#!` line to launch python3? And make 
the switch official?

**Comment by gdevenyi** [comment]
We could, but if we're not really using any python3 special sauce, it would be nice for broad compatibility.

**Comment by gvwilson** [comment]
Fixed by @gdevenyi's `from __future__` patch.
