### ISSUE TITLE
Document procedure for installing necessary R packages.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/styles#87]

**Comment by gvwilson** [comment]
@fmichonneau can you please provide notes?

**Comment by fmichonneau** [comment]
sorry I had missed this. Where would you like me to add it?

**Comment by fmichonneau** [comment]
sorry I had missed this. Where would you like me to add it?

**Comment by gvwilson** [comment]
Can you please PR the https://github.com/swcarpentry/lesson-example 
repo?  If there's something like Python's requirements.txt (which is 
used to automate the install process), it should go in the 'styles' repo 
(this one), but the documentation should go in the example lesson.
Thanks,
Greg
