### ISSUE TITLE
allow for easy linking to examples/exercises etc.

### ISSUE THREAD

**Issue by btel** [swcarpentry/styles#94]
Exercises, call-outs and examples have ids (such as "turn-a-string-into-a-list"), which can be used for linking:

http://swcarpentry.github.io/python-novice-inflammation/03-lists/#turn-a-string-into-a-list

but to get this link it's necessary to inspect the html code. It would be good to add possibility for such linking directly on the web page.
## Use case

You may want to copy a link to particular example/call-out to etherpad during the lesson.
## Solution

Provide a link button next to the section title, which redirects to the webpage using URL with the id. A good example is on read the docs website (the link appears only when you hoover your mouse above the section name):

![rtfd_link](https://cloud.githubusercontent.com/assets/41565/18026887/dd686d6c-6c54-11e6-8f11-91a15a0779dc.png)

http://docs.readthedocs.io/en/latest/features.html#read-the-docs-features

**Comment by rgaiacs** [comment]
@btel Thanks for the issue. This is a feature that I believe all instructors and learners would like to have but not easy to have due our current workflow with GitHub pages. Kramdown, our Markdown to HTML engine, doesn't support it (see https://github.com/gettalong/kramdown/issues/188 for more details), we can't run any Jekyll plugin on GitHub pages, I will vote against using Javascript to add the link and have the link embed on the Markdown file is prone error.

**Comment by btel** [comment]
@rgaiacs Thanks for investigating this issue. Indeed the only solution that I found on the web is to use JS. I agree that it can cause more trouble than aid. It seems that the IDs are auto-generated based on exercise titles (by replacing spaces with minuses), so it's not  hard to compose the urls manually. How about documenting this not-so-obvious feature somewhere? Would you suggest a good place for this (FAQ, instructor notes, etc.)?

**Comment by rgaiacs** [comment]
> Indeed the only solution that I found on the web is to use JS. I agree that it can cause more trouble than aid.

:-)

> It seems that the IDs are auto-generated based on exercise titles (by replacing spaces with minuses), so it's not hard to compose the urls manually.

Kramdown will add `id` for all headers. E.g.

~~~
$ kramdown <<<"# foo"
<h1 id="foo">foo</h1>
$ kramdown <<<"## foo"
<h2 id="foo">foo</h2>
$ kramdown <<<"# foo bar"
<h1 id="foo-bar">foo bar</h1>
$ kramdown <<<"# foo (bar)"
<h1 id="foo-bar">foo (bar)</h1>
$ kramdown <<<"# fóõ"      
<h1 id="f">fóõ</h1>
~~~

But not only spaces are replace with minuses.

> so it's not hard to compose the urls manually.

I will disagree (see the last two examples).

> How about documenting this not-so-obvious feature somewhere?

+1

> Would you suggest a good place for this (FAQ, instructor notes, etc.)?

Can you send a pull request to https://github.com/swcarpentry/lesson-example? Thanks in advance.

**Comment by btel** [comment]
Thanks! Here is the PR:

https://github.com/swcarpentry/lesson-example/pull/102
