### ISSUE TITLE
Add link to Setup instructions on index page

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/styles#97]
People are having a hard time finding the data for the lessons, and not knowing to look at the Setup tab. Add something to index to point them in the right direction.

Thanks to @erdavenport for suggesting this update.

**Comment by rgaiacs** [comment]
I think that this issues belongs to https://github.com/swcarpentry/lesson-example/.

**Comment by iglpdc** [comment]
Yes, I agree with @tracykteal.

**Comment by tracykteal** [comment]
@rgaiacs it has to be fixed here in the 'styles' repo for it to affect lesson-example and all the other lesson repos. The lesson repos have this as an upstream repo, so they can pull updates to the template from here.

**Comment by tracykteal** [comment]
One idea is to do it as in http://swcarpentry.github.io/python-novice-inflammation/ with adding a 'Getting Started' line to the index page.

**Comment by rgaiacs** [comment]
>  it has to be fixed here in the 'styles' repo for it to affect lesson-example and all the other lesson repos.

My bad. :-( I'm getting confuse with what each repo host last year and now.

**Comment by tracykteal** [comment]
This also was addressed in the Lesson Infrastructure meeting as something that needed a decision and an update in the template, so that it was consistent across all lessons. 

https://github.com/swcarpentry/board/blob/master/subcommittees/lessons/2017-02-08.md

**Comment by tracykteal** [comment]
Also being discussed at https://github.com/swcarpentry/make-novice/issues/80

**Comment by gcapes** [comment]
Thanks @tracykteal

**Comment by lexnederbragt** [comment]
There is a potential for confusion in that 'Setup' is used on the workshop websites to mean 'installation of software' (http://swcarpentry.github.io/workshop-template/#setup), while on each lesson page it (as far as I know) 'Setup' refers to 'download this file and unzip it' or something similar.

Ideally, the lesson 'Setup' page would also address installation issues. However, instructions for this should ideally be in one place (and perhaps the index.html page of the workshop website is not the best place).

Fixing all this may be a bit of work...?

**Comment by vuw-ecs-kevin** [comment]
FYI

The "shell-extras" lesson, rendered under the current template, as in my fork here

  https://github.com/vuw-ecs-kevin/shell-extras/tree/swap-to-jekyll-2

has both the Setup menu-item and a "ahead of Schedule" item on the 
front page. (See images)

Clearly the actual setup page here, in common with a number of the episodes,
only has some outline text.

Note that the Setup item in the Schedule was already there when I started rendering
the old content with the new template, so it's clearly something that SWC has done
in the past, whereas the current renderings got the menu item from the new template.

![20170310-swc-01](https://cloud.githubusercontent.com/assets/12106904/23770276/51208a12-0577-11e7-866d-e47a0a5d4948.png)

![20170310-swc-02](https://cloud.githubusercontent.com/assets/12106904/23770285/54f00348-0577-11e7-99a7-b8704fa67eaf.png)

Hoping that helps remind you of your history !

**Comment by rgaiacs** [comment]
I'm closing this as fixed.

> One idea is to do it as in http://swcarpentry.github.io/python-novice-inflammation/ with adding a 'Getting Started' line to the index page.

This is the solution that we adopted.
